~ removed a few todos from auto generated php unit stubs (+27 squashed commits) Squashed commits: [b606dd9] ~ try to use ChildDefinition, fallback to DefinitionDecorator [b594679] ~ fixed refactored behavior in AuthorizedFormHandler [4c390ad] ~ fixed unit test for OAuthFactory to test with ChildDefinition or DefinitionDecorator, depending on what's available [dedbdce] ~ bump minimum php requirements to 5.5 [0dbd3d7] ~ fixing various compatibility issues
Fatal error: Call to undefined method FOS\OAuthServerBundle\Tests\DependencyInjection\Compiler\GrantExtensionsCompilerPassTest::expectExceptionMessage() in /Users/nikola/Projects/Personal/FOSOAuthServerBundle/Tests/DependencyInjection/Compiler/GrantExtensionsCompilerPassTest.php on line 165

Fatal error: Call to undefined method FOS\OAuthServerBundle\Tests\Controller\AuthorizeControllerTest::createMock() in /Users/nikola/Projects/Personal/FOSOAuthServerBundle/Tests/Controller/AuthorizeControllerTest.php on line 171
[fd8dc00] ~ changes to fix error message: Cannot mock Symfony\Component\Routing\Router::addExpressionLanguageProvider() because a class or interface used in the signature is not loaded
[f1afabc] ~ changes to fix error message:
Cannot mock Symfony\Component\DependencyInjection\ContainerBuilder::addExpressionLanguageProvider() because a class or interface used in the signature is not loaded
[ab166f6] - removing php 5.4 env from travis ci
[24b9293] ~ corrected logic in the unit test and in the form handler; it was simplified correctly, but one case was returning NULL instead of FALSE as it initially did
[d3ee202] ~ re-adding back support for PHP 5.x in travis builds
[3f0e1d0] ~ updated unit test not to fail when trigger user deprecation warning
[cb42611] ~ updated travis-ci configuration to not generate builds for unsupported php versions
[936ce90] ~ using symfony/phpunit-bridge to negate the effect of time sensitive tests
[31b8206] ~ trying to fix the EngineInterface error in travis-ci

Fatal error: Interface 'Symfony\Component\Templating\EngineInterface' not found in /home/travis/build/FriendsOfSymfony/FOSOAuthServerBundle/vendor/symfony/framework-bundle/Templating/EngineInterface.php on line 22
[255e858] + added missing unit tests
[dba158e] ~ refactored unit test for OAuthProvider
[3c414d8] + added unit test for OAuthFactory
[dad5b08] + added unit test for OAuthToken
[5bd691a] ~ improved unit test for AuthorizeFormType
[ec0988b] + unit test for AuthorizeFormHandler
[5ca1ce9] ~ slightly refactored AuthorizeFormHandler
[1115345] ~ refactoring of AuthorizeController::getClient() to improve readability and make the code easier to follow and understand
[d9b75de] ~ simplifying the AuthorizeController test
[e0f0574] + added unit test for AuthorizeController
[818c526] ~ fixed unit test for FOSOAuthServerBundle for when using Symfony 2.0
[18d8656] + unit test for FOSOAuthServerBundle
[3d1728f] ~ improved unit tests

+ unit test for FOSOAuthServerBundle

~ fixed unit test for FOSOAuthServerBundle for when using Symfony 2.0

+ added unit test for AuthorizeController

~ simplifying the AuthorizeController test

~ refactoring of AuthorizeController::getClient() to improve readability and make the code easier to follow and understand

~ slightly refactored AuthorizeFormHandler

+ unit test for AuthorizeFormHandler

~ improved unit test for AuthorizeFormType

+ added unit test for OAuthToken

+ added unit test for OAuthFactory

+ added missing unit tests

~ using symfony/phpunit-bridge to negate the effect of time sensitive tests

~ updated unit test not to fail when trigger user deprecation warning

~ corrected logic in the unit test and in the form handler; it was simplified correctly, but one case was returning NULL instead of FALSE as it initially did

~ changes to fix error message:
Cannot mock Symfony\Component\DependencyInjection\ContainerBuilder::addExpressionLanguageProvider() because a class or interface used in the signature is not loaded

~ changes to fix error message: Cannot mock Symfony\Component\Routing\Router::addExpressionLanguageProvider() because a class or interface used in the signature is not loaded

~ fixing various compatibility issues

Fatal error: Call to undefined method FOS\OAuthServerBundle\Tests\DependencyInjection\Compiler\GrantExtensionsCompilerPassTest::expectExceptionMessage() in /Users/nikola/Projects/Personal/FOSOAuthServerBundle/Tests/DependencyInjection/Compiler/GrantExtensionsCompilerPassTest.php on line 165

Fatal error: Call to undefined method FOS\OAuthServerBundle\Tests\Controller\AuthorizeControllerTest::createMock() in /Users/nikola/Projects/Personal/FOSOAuthServerBundle/Tests/Controller/AuthorizeControllerTest.php on line 171

~ fixed unit test for OAuthFactory to test with ChildDefinition or DefinitionDecorator, depending on what's available

~ fixed refactored behavior in AuthorizedFormHandler

~ try to use ChildDefinition, fallback to DefinitionDecorator

~ removed a few todos from auto generated php unit stubs